cho-pul-ha-na/choful-market

src/components/atoms/Input/Input.jsx, src/components/atoms/Input/Input.stories.js
=> FE-8 Feat : Input 컴포넌트 및 스토리 개발

src/components/atoms/Label/Label.jsx, src/components/atoms/Label/Label.stories.js
1. Label 컴포넌트와 스토리 파일을 개발하였습니다.
=> FE-12 Feat : Label 컴포넌트 및 스토리 개발

src/App.jsx, src/index.jsx, src/pages/ChatList.jsx, src/pages/ChatRoom.jsx, src/pages/EmailLogin.jsx, src/pages/EmailSignUp.jsx, src/pages/Home.jsx, src/pages/Login.jsx, src/pages/MyProfile.jsx, src/pages/MyProfileAddProduct.jsx, src/pages/MyProfileModification.jsx, src/pages/Post.jsx, src/pages/PostUpload.jsx, src/pages/Search.jsx, src/pages/SetProfile.jsx, src/pages/YourProfile.jsx
1. Router 초기 세팅
2. Router 세팅을 위한 pages 폴더 및 page 파일 생성
=> FE-15 Feat : Router 초기 세팅

src/components/atoms/Icon/Icon.stories.js, src/components/modules/Header/Header.jsx
1. Icon의 isLink를 불리언 값으로 변경했습니다.
2. Icon의 스토리파일에 isLinkNav를 삭제했습니다.
3. Header 모듈을 개발했습니다.
=> FE-11 Refactor : 코드리뷰 받은 부분 수정

.prettierrc
1. .prettierrc 파일의 jsxSingleQuote를 통일성을 위해 true로 변경했습니다.
=> Chore : .prettierrc 파일 jsxSingleQuote 변경

src/App.jsx, src/components/atoms/Icon/Icon.jsx, src/components/modules/Nav/Nav.jsx, src/index.jsx
1. Icon에 isLink 불리언 값으로 수정했습니다. 
3. Icon에 Link태그로 받을 Icon 컴포넌트 props값을 넘겨 줄 수 있도록 수정했습니다.
=> Refactor : 코드리뷰 받은 부분 수정

src/App.jsx, src/components/atoms/Button/Button.jsx, src/components/modules/Header/Header.jsx
1. Button.jsx에 btn_header 클래스 추가했습니다.
2. 클래스 2개 이상 갖는 컴포넌트의 className코드를 좀 더 간결하게 백틱으로 수정했습니다.
3. 빈 값이 들어가는 className의 삼항연산자 String값을 직관적으로 들어오게 null로 수정했습니다.
=> FE-19 Refactor : 코드리뷰 받은 부분 수정

src/components/modules/Nav/Nav.jsx
1. Nav바가 페이지 하단에 위치하도록 수정했습니다.
2. 반응형으로 보일 수 있도록 width값 조정했습니다.
=> FE-16 Design : Nav 바 CSS 코드 수정

src/components/atoms/Label/Label.jsx, src/components/modules/PostUserInfo/PostUserInfo.jsx, src/components/modules/UserInformation/UserInformation.jsx, src/pages/ChatList.jsx, src/pages/Followers/Followers.jsx, src/pages/Search.jsx
1. Chatlist, Search, Followers 페이지 제작
2. PostUserInfo 모듈제작
3. UserInformation 모듈 제작을 통해 모듈화 하려 했으나 실패 추후 리팩토링 과정에서 모듈화 진행 예정
4. Label props 수정
=> Myeong seok

src/components/modules/Header/Header.jsx, src/components/modules/Nav/Nav.jsx
header와 nav에 z-index 및 background-color 추가했습니다!
=> FE-19 Style : z-index 및 background-color 추가

src/components/modules/DropUp/DropUp.jsx, src/components/modules/DropUp/DropUp.stories.js, src/components/modules/Modal/Modal.jsx, src/components/modules/Modal/Modal.stories.js, src/theme.js
1. Modal과 DropUp 창 UI를 개발하였습니다.
2. theme.js에 borderRadius를 추가하였습니다.
=> FE-22 Feat : Modal 컴포넌트 및 스토리 개발

src/App.jsx, src/components/atoms/Button/Button.jsx, src/components/modules/Post/Post.jsx, src/components/modules/Post/Post.stories.js, src/pages/404/404.jsx, src/pages/Home.jsx, src/pages/Home/Home.jsx, src/pages/SplashScreen/SplashScreen.jsx
1. 나중에 추가로 props가 들어오더라도 사용할 수 있게 스프레드 문법을 사용해서 props를 넣어줬습니다.
2. onClick 함수가 작동할 수 있도록 props를 추가했습니다.
3. 화면 전체를 가리기 위한 height 설정
4. Logo 이미지만 fadeInOut 애니메이션 설정
5. Home 피드 화면 등에 사용하는 Post 모듈을 개발했습니다
6. Home 페이지 개발했습니다
=> FE-20 Feat : Home 페이지 개발 

src/pages/ChatRoom.jsx
=> FE-23 Feat : chat room UI 제작

src/components/common/commonWrapper.js, src/components/modules/Header/Header.jsx, src/components/modules/Nav/Nav.jsx, src/pages/Home/Home.jsx
1. Home, Header, Nav 에만 적용을 했습니다. 나머지는 개발을 하면서 해보시는게 좋아보입니다.
=> FE-26 Feat : 공통 Wrapper 개발

src/App.jsx, src/pages/MyProfileEdit.jsx, src/pages/MyProfileModification.jsx, src/pages/Post.jsx, src/pages/PostDetail.jsx
1. API 명세를 참조해서 URL을 수정했습니다.
2. Router 수정을 인한 파일명을 수정했습니다.
=> FE-27 Refactor : Router URL 수정

src/components/atoms/Icon/Icon.jsx, src/components/atoms/Icon/Icon.stories.js, src/components/modules/ForSale/ForSale.jsx, src/components/modules/Header/Header.jsx, src/components/modules/MyprofileBtn/MyProfileBtn.jsx, src/components/modules/Nav/Nav.jsx, src/components/modules/PostUserInfo/PostUserInfo.jsx, src/components/modules/ProfileInfo/ProfileInfo.jsx, src/components/modules/ProfilePost/ProfilePost.jsx, src/components/modules/YourProfileBtn/YourProfileBtn.jsx, src/font/font.css, src/index.jsx, src/pages/MyProfile.jsx, src/pages/YourProfile.jsx
1. Profile에 들어가는 모듈 및 페이지를 개발했습니다.
2. 판매중인 상품이 들어가는 ForSale 모듈을 개발했습니다.
3. Header, Nav에 CommonWrapper 적용하기 위해 코드 수정했습니다.
=> FE-21 Feat : Profile 페이지 ui 개발

src/App.jsx, src/components/atoms/SnsButton/SnsButton.jsx, src/pages/SNSLogin/SNSLogin.jsx
1. SNS 로그인 페이지 제작
2. SNS버튼 수정
3. App.jsx 파일 수정
=> Fe 25 feat sns login

src/components/modules/Nav/Nav.jsx
nav에 hide 클래스를 추가해 nav가 없는 페이지에 숨김처리 하였습니다.
=> FE-16 Refactor : url 경로에 따른 nav 숨김처리

src/components/atoms/Icon/Icon.jsx, src/components/modules/Header/Header.jsx, src/components/modules/Nav/Nav.jsx
=> FE-19 Feat : 뒤로가기 버튼 기능 추가

src/App.jsx, src/components/atoms/Input/Input.jsx, src/pages/PostUpload/PostUpload.jsx
1. App.jsx에서 import 경로를 수정했습니다.
2. Upload 페이지의 ui를 개발했습니다.
3. Input.jsx 컴포넌트 파일 수정하여 textarea 태그에서 입력할 때 자동으로 높이가 늘어나는 기능을 추가했습니다.
=> FE-24 Feat : 포스트를 업로드하는 Upload 페이지 개발

src/App.jsx, src/components/modules/InputBox/InputBox.jsx, src/components/modules/InputBox/InputBox.stories.js, src/components/modules/InputForm/InputForm.jsx, src/components/modules/InputForm/InputForm.stories.js, src/pages/EmailLogin.jsx, src/pages/EmailLogin/EmailLogin.jsx, src/pages/EmailSignUp/EmailSignUp.jsx, src/pages/Login.jsx
1. EmailLogin 로그인 화면 구현하였습니다.
2. InputBox와 InputForm 모듈을  개발하였습니다.
3. EmailSignUp페이지는 아직 구현 중입니다. 오늘 내로 올리도록 하겠습니다!
얼마나 진행되었는지 궁금하셨을텐데 기다려주시고 항상 도움주셔서 감사합니다.
얼꼴 파이탱
=> FE - 14 Feat : EmailLogin 페이지 및  InputBox/InputForm 모듈구현

src/App.jsx, src/pages/EmailLogin/EmailLogin.jsx, src/pages/EmailSignUp.jsx, src/pages/EmailSignUp/EmailSignUp.jsx
1. EmailSingUp 구현 완료하였습니다.
2. EmailLogin 페이지의 margin-top을 주어 피그마와 유사도를 높였습니다.
3. EmailLogin 페이지의 '이메일로 회원가입'을 EmailSignUp과 링크로 연결하였습니다.
=> FE - 14 Feat : EmailSignUp 페이지 구현 및 EmailLogin 페이지 수정

src/App.jsx, src/components/modules/InputForm/InputForm.jsx, src/pages/MyProfileEdit.jsx, src/pages/MyProfileEdit/MyProfileEdit.jsx
1. MyProfileEdit 페이지를 개발했습니다.
2. MyProfileEdit 폴더 생성으로 인해 App.jsx의 import 경로를 수정했습니다.
3. btnLabel 유무에 따라 Button 컴포넌트가 보여지고 안보여지는 조건문을 추가했습니다.
=> FE-30 Feat : MyProfileEdit 페이지 개발

package-lock.json, src/App.jsx, src/atoms.js, src/pages/EmailLogin/EmailLogin.jsx, src/pages/EmailSignUp/EmailSignUp.jsx, src/pages/SNSLogin/SNSLogin.jsx, src/pages/SplashScreen/SplashScreen.jsx
1. EmailLogin 파일에서 이메일 비밀번호 입력 시 로그인버튼 활성화하였습니다.
2. 올바른 이메일 비밀번호 입력시 홈피드로 이동하게 만들었습니다.
3. 틀린 이메일 비밀번호 입력시 로그인버튼 활성화 후 '이메일 또는 비밀번호가 일치하지 않습니다.' 경고 메세지  등장하게 만들었습니다.
4. App.jsx 파일에서 Route에서 Navigate로 변경하였습니다.
5. atom.js에서 isLogin 생성하였습니다.
6. SNSLogin.jsx 파일에서 SplashScreen 파일을 임포트하였습니다.
7. SplashScreen.jsx 파일에서 Wrapper에 position과 z-index 부여하였습니다.
=> FE-14 Feat : 로그인페이지 기능구현

src/atoms.js, src/components/modules/Header/Header.jsx, src/components/modules/InputBox/InputBox.jsx, src/components/modules/MyprofileBtn/MyProfileBtn.jsx, src/components/modules/Nav/Nav.jsx, src/pages/EmailLogin/EmailLogin.jsx, src/pages/EmailSignUp/EmailSignUp.jsx, src/pages/MyProfileEdit/MyProfileEdit.jsx
1. 응답받은 data를 저장할 userData 전역변수를 추가했습니다.
2. 프로필 수정 페이지에서 accountname, username값을 입력했을 때 적합한 에러메시지가 뜰 수 있게 했습니다.
3. 수정한 프로필 값을 서버에 보내 응답받은 데이터 값으로 전역변수에 있는 유저 정보를 갱신하는 코드를 추가했습니다.
=> FE-30 Feat :  프로필 수정 페이지 기능 개발

src/components/modules/ProfileInfo/ProfileInfo.jsx
1. 서버에서  받아온 데이터를 마이프로필 창에 뿌려주도록 했습니다
=> FE-35 Feat : 마이프로필 정보 받아오

src/App.jsx, src/components/modules/Header/Header.jsx, src/components/modules/Post/Post.jsx, src/pages/PostDetail/PostDetail.jsx
1. Post.jsx 파일에서 좋아요(하트)버튼을 클릭하면 하트가 채워지고, 숫자가 올라갑니다. 또 다시 누르면 빈 하트가 되면서 숫자가 감소하게 구현하였습니다.
2. App.jsx 파일에서 라우트를 '/post/:post_id'에서 '/post/:id'로 변경하였습니다.
3. Header.jsx파일에서 navigate 경로를 'profile/:id'에서 `profile/${accountname}`으로 변경하였습니다.
4. PostDetail.jsx파일에서 params, postID 선언 대신 {id}로 변경하여 선언하였습니다. 또한 axios.get 요청에 ${postId} 대신 ${id}로 변경해주었습니다.
=> FE-37 Feat : 좋아요 기능 구현

src/components/modules/Post/Post.jsx, src/components/modules/ProfileInfo/ProfileInfo.jsx, src/components/modules/YourProfileBtn/YourProfileBtn.jsx
1. Post.jsx 수정은 Follow 기능 개발을 위해 임의로 해놓은 것입니다.
2. YourProfileBtn 내부 팔로우, 언팔로우 버튼에 클릭 이벤트로 follow, unfollow api를 사용해 팔로우 기능을 구현했습니다.
3. YourProfileBtn의 상위 컴포넌트인 ProfileInfo에 props를 전달하기 위해 setFollowerCountFunc, setFollowingCountFunc 함수 props를 만들어 사용했습니다.
4. YourProfileBtn에 사용자를 팔로우를 했는지 안했는지 여부를 체크하는 checkFollow 함수를 useEffect를 활용해 페이지에 들어올때마다 check하게 했습니다.
=> FE-41 Feat : Follow 기능 개발

src/components/modules/Post/Post.jsx, src/pages/Home/Home.jsx
1. post/feed api를 사용해 Home 페이지에 팔로잉 유저 게시물을 불러왔습니다.
2. 약간의 UI 수정을 했습니다.
3. feedPostData의 length가 0보다 클 경우에 피드를 보여주고 아니면 검색하기 버튼과 로고를 보여줍니다.
=> FE-20 Feat : Home 피드 게시물 불러오기

src/components/modules/Comment/Comment.jsx, src/components/modules/DropUp/DropUp.jsx, src/components/modules/Modal/Modal.jsx, src/components/modules/Post/Post.jsx, src/components/modules/PostCommentInput/PostCommentInput.jsx, src/pages/PostDetail/PostDetail.jsx
1. 서버에서 보내주는 데이터를 통해 게시글의 댓글을 보여주는 함수를 추가했습니다.
2. 작성한 시간과 현재 시간의 차를 구해 분으로 변경해준 후 1분 미만이면 '방금', 60분 미만이면 분으로 표시, 그 이후는 날짜로 표시하는 함수를 추가했습니다.
3. 게시글에 댓글을 작성할 수 있는 기능을 개발했습니다.
4. Post.jsx 파일에서 wrapper를 씌우는 과정에서 중복으로 쓰인 margin값을 수정했습니다.
5. 전역변수에 저장된 accountname과 댓글의 accountname을 비교하여 본인이 작성한 댓글이면 삭제가 가능한 기능을 추가했습니다.
6. DropUp과 Modal 컴포넌트를 추가했습니다.
7. 댓글이 삭제된 후 다시 댓글리스트를 다시 받아와서 변경된 댓글리스트를 보여줍니다.
확인 부탁드립니다 😊
=> FE-42 Feat: 댓글 기능 개발 

src/atoms.js, src/components/atoms/Input/Input.jsx, src/components/modules/Header/Header.jsx, src/components/modules/InputBox/InputBox.jsx, src/pages/MyProfileAddProduct/MyProfileAddProduct.jsx
1. 상품등록에 필요한 Atom 추가
2. 상품등록에 사용될 recoilKey 추가
3. 불필요한 코드제거
4. Header의 저장버튼을 통해 상품등록이  가능하도록 구현
5. 상품 이미지 등록 기능 개발
=> FE-40 Feat: 상품등록기능 개발

package-lock.json, package.json, src/App.jsx, src/atoms.js
1. recoil-persist를 설치했습니다.
2. recoil-persist를 사용해 새로고침이 되더라도 아톰의 값이 남아있게 하는 기능을 개발했습니다.
3. recoil-persist를 사용해 로그인 상태를 체크하는 함수를 간소화 했습니다.
=> FE-47 Feat : recoil-persist 사용해 아톰의 상태유지 기능 개발

src/components/atoms/Input/Input.jsx, src/components/modules/Header/Header.jsx, src/pages/MyProfileAddProduct/MyProfileAddProduct.jsx
1. FE-40 Refactor: 상품등록 페이지 UI 개선
2. FE-40 Refactor: Input창 기본 스타일 제거
3. FE-40 Refactor: Header내 버튼 활성화 작업 진행
=> FE-40 Refactor: 상품등록 페에지 UI/ UX 개선

src/components/modules/Post/Post.jsx
1. 게시글에 이미지가 두 개 이상일경우 map을 돌려 두 개 이상의 이미지도 볼 수 있도록 코드를 수정했습니다.
=> FE-39 Refactor : 게시글에서 이미지 보여주는 코드 수정

src/components/modules/Header/Header.jsx
1. 로그아웃 기능을 구현했습니다.
2. 토큰을 삭제하고 전역변수의 isLogin 값을 false로 변경합니다.
=> FE-48 Feat : 로그아웃 기능 구현

src/components/modules/Comment/Comment.jsx
1. 댓글의 작성자 프로필을 클릭하면 작성자의 프로필로 이동하도록 Link태그를 추가했습니다.
=> FE-42 Refactor : 댓글에 Link 태그 추가

src/pages/Followers/Followers.jsx
1. 한 눈에 잘 들어오도록 팔로우 사이의 gap을 조정했습니다.
=> FE-43 Refactor : 팔로우리스트 gap 조정

src/components/modules/Post/Post.jsx
1. 게시물 이미지가 여러개일 경우 이미지 정렬이 세로로 되어있는것을 가로로 바꾸고 overflow-x 를 auto를 주었습니다.
=> FE-20 Fix : 홈 피드 게시물 이미지 세로로 보이는 현상 해결

src/components/atoms/Icon/Icon.jsx, src/components/modules/GalleryPost/GalleryPost.jsx
1. 갤러리 모드에서 이미지가 여러장일 경우 에러가 나는 부분을 수정했습니다.
2. 여러장일 경우 첫번째 이미지가 나타나고 이미지에 여러장임을 알려주는 갤러리 아이콘을 띄웁니다.
3. Icon의 위치조정을 위해 props로 position, top, right를 받는 코드를 추가했습니다.
=> FE-38 Fix : 프로필 페이지에서 갤러리 에러 수정

src/components/modules/Header/Header.jsx
1. 프로필 수정 페이지에서 userName, userIntro, accountName 입력이 완료되면 버튼이 활성화 되도록 수정했습니다
=> FE-40 Refactor: 프로필수정 버튼 활성화

src/components/modules/Header/Header.jsx, src/pages/MyProfileEdit/MyProfileEdit.jsx
=> FE-49 Fix : 프로필수정 에러 해결

src/components/modules/Header/Header.jsx
1. 헤더 파일에서 포스트 업로드와 포스트 수정함수가 충돌하여 함수가 실행되는 조건문을 수정했습니다.
=> FE-49 Fix : 포스트 업로드 함수 충돌 해결

src/components/modules/Post/Post.jsx
1. 게시글의 줄바꿈이 자동으로 적용되도록 수정했습니다
=> FE-40 Refactor: 게시글 줄바꿈 활성화

src/components/modules/DropUp/DropUp.jsx, src/components/modules/Modal/Modal.jsx, src/components/modules/Nav/Nav.jsx
1. DropUp과 Modal창에 cursor가 pointer로 나타나게 코드를 추가했습니다.
2. CommonWrapper에 들어가게 된 padding 값이 nav에 영향을 끼치지 않게 수정했습니다.
=> FE-22 Design : cursor 코드 추가 

src/components/modules/LikeBtn/LikeBtn.jsx, src/components/modules/Post/Post.jsx
1. 좋아요 버튼을 컴포넌트화 하여 Post 파일에 넣었습니다.
=> FE-37 Refactor : 좋아요 버튼 컴포넌트화

src/components/modules/Header/Header.jsx
1. 프로필 페이지에서 DropUp창이 제일 앞쪽에 배치될 수 있도록 코드 위치를 변경했습니다.
=> FE-49 Refactor : DropUp창 위치변경

src/components/atoms/Button/Button.stories.js, src/components/atoms/Img/Img.stories.js, src/components/atoms/Profile/Profile.stories.js, src/components/modules/Comment/Comment.jsx, src/components/modules/Comment/Comment.stories.js, src/components/modules/Comment/style.js, src/components/modules/CustomFileInput/CustomFileInput.jsx, src/components/modules/CustomFileInput/CustomFileInput.stories.js, src/components/modules/CustomFileInput/style.js, src/components/modules/DropUp/DropUp.jsx, src/components/modules/DropUp/DropUp.stories.js, src/components/modules/DropUp/style.js, src/components/modules/ForSale/ForSale.jsx, src/components/modules/ForSale/style.js, src/components/modules/GalleryPost/GalleryPost.jsx, src/components/modules/GalleryPost/style.js, src/components/modules/Header/Header.jsx, src/components/modules/Header/style.js, src/components/modules/InputBox/InputBox.jsx, src/components/modules/InputBox/InputBox.stories.js, src/components/modules/InputBox/style.js, src/components/modules/LikeBtn/LikeBtn.jsx, src/components/modules/LikeBtn/style.js, src/components/modules/Modal/Modal.jsx, src/components/modules/Modal/style.js, src/components/modules/MyprofileBtn/MyProfileBtn.jsx, src/components/modules/MyprofileBtn/style.js, src/components/modules/Post/Post.stories.js
1. 스타일 컴포넌트 분리했습니다
2. import순서 정리했습니다.
=> FE-51 Refactor : modules내 스타일컴포넌트 분리

src/App.jsx, src/components/modules/Comment/Comment.stories.js, src/components/modules/Comment/style.js, src/pages/ChatList/ChatList.jsx, src/pages/Chatroom/ChatRoom.jsx, src/pages/Followers/Followers.jsx
=> FE-51 Refactor : 에러수정

src/App.jsx, src/components/modules/Nav/Nav.jsx, src/components/modules/Nav/Nav.stories.js, src/components/modules/Nav/style.js, src/components/modules/Post/Post.jsx, src/components/modules/Post/style.js, src/components/modules/PostCommentInput/PostCommentInput.jsx, src/components/modules/PostCommentInput/style.js, src/components/modules/PostUserInfo/PostUserInfo.jsx, src/components/modules/PostUserInfo/style.js, src/components/modules/ProfileInfo/ProfileInfo.jsx, src/components/modules/ProfileInfo/style.js, src/components/modules/ProfilePost/ProfilePost.jsx, src/components/modules/ProfilePost/style.js, src/components/modules/UserInformation/UserInformation.jsx, src/components/modules/UserInformation/style.js, src/components/modules/YourProfileBtn/YourProfileBtn.jsx, src/components/modules/YourProfileBtn/style.js
1. Nav~YourProfileBtn 의 스타일컴포넌트를 분리하였습니다. 
2. import 순서를 정리하였습니다.(사실 어떻게 정리하는지 잘 모릅니다. 알려주시면 감사히 수정하겠습니다.)
그 외 수정사항이 있다면 언제든 코멘트 남겨주세요.
늘 도움주셔서 감사합니다.
=> FE-56 Refactor : Modules2 스타일 컴포넌트 분리

src/components/modules/Post/Post.jsx, src/components/modules/YourProfileBtn/YourProfileBtn.jsx
1. Post, YourProfileBtn.jsx 파일의 import를 정리하였습니다.
=> FE-56 Refactor : import 정리

src/App.jsx, src/apis/apis.js, src/components/modules/Comment/Comment.jsx, src/components/modules/CustomFileInput/CustomFileInput.jsx, src/components/modules/DropUp/DropUp.jsx, src/components/modules/ForSale/ForSale.jsx, src/components/modules/GalleryPost/GalleryPost.jsx, src/components/modules/Header/Header.jsx, src/components/modules/LikeBtn/LikeBtn.jsx, src/components/modules/Post/Post.jsx, src/components/modules/PostCommentInput/PostCommentInput.jsx, src/components/modules/PostUserInfo/PostUserInfo.jsx, src/components/modules/ProfileInfo/ProfileInfo.jsx, src/components/modules/ProfilePost/ProfilePost.jsx, src/components/modules/YourProfileBtn/YourProfileBtn.jsx, src/pages/ChatList/ChatList.jsx, src/pages/Chatroom/ChatRoom.jsx, src/pages/EmailLogin/EmailLogin.jsx, src/pages/EmailSignUp/EmailSignUp.jsx, src/pages/Followers/Followers.jsx, src/pages/Home/Home.jsx, src/pages/MyProfileAddProduct/MyProfileAddProduct.jsx, src/pages/MyProfileEdit/MyProfileEdit.jsx, src/pages/PostDetail/PostDetail.jsx, src/pages/PostUpload/PostUpload.jsx, src/pages/SetProfile/SetProfile.jsx
1. App.jsx 내 쓰지 않는 hook들을 지웠습니다.
2. 라우팅한 url 외의 모든 url로 접근하려 하면 404 페이지가 뜨게 라우터를 추가했습니다.
3.  hearted를 사용해 좋아요를 눌렀던 게시글을 기억해 계속 하트가 차있도록 했습니다.
4. API 즉, axios 함수들을 따로 관리하기 위해 apis.js 파일을 생성했습니다.
5. axios 함수들의 재사용성과 유지보수를 용이하게 하기 위해 나누었습니다.
6. 추가적으로 import, handle 함수명 역시 변경했습니다.
=> FE-54 Refactor : API 파일 분기
